// Generated by scripts/build-hero-frames.mjs — do not edit by hand.
export const heroFrames = {
  widths: [1080, 1600, 2000] as const,
  count: 120,
  path: (width: number, index: number) =>
    `/media/hero/frames/${width}/${String(index).padStart(3, "0")}.webp`,
} as const;

export type HeroFramesManifest = typeof heroFrames;
