// Generated by scripts/build-rx-brain-frames.mjs — do not edit by hand.
export const rxBrainFrames = {
  widths: [1080, 1600, 2000] as const,
  count: 178,
  path: (width: number, index: number) =>
    `/media/rx-brain/frames/${width}/${String(index).padStart(3, "0")}.webp`,
} as const;

export type RxBrainFramesManifest = typeof rxBrainFrames;
